# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-16 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0032_auto_20180405_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='product_input_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
