# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0033_auto_20180416_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='labware_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
