# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-10 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_auto_20180301_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerset',
            name='alert_linked_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triggerset',
            name='alert_user_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
