# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-29 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0028_auto_20181029_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('species', models.PositiveIntegerField(default=0)),
                ('gender', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_type', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=45)),
                ('result', models.TextField(max_length=500)),
                ('value', models.CharField(max_length=45)),
                ('img', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_identifier', models.CharField(max_length=45)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='animal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='protocol',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='storing_conditions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unstained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Product'),
        ),
        migrations.AddField(
            model_name='animal',
            name='study_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.StudyGroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='animal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Animal'),
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Container'),
        ),
    ]
