# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-29 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20181029_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroup',
            options={'ordering': ('group_identifier',)},
        ),
    ]
