# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20181029_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unstained',
            field=models.BooleanField(default=0),
        ),
    ]
